Refactoring

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -9,87 +9,99 @@ export PATH=/usr/local/bin:$PATH
 
 # Git repository absolute path
 git_root=`git rev-parse --show-toplevel`
-# Create array of all staged files
-git_diff=`git diff --name-only --cached | grep ".*\.sketch$"`
+# Unzipped Sketch files path
+unzipped_root="$git_root/_unzipped"
+# Untouched Sketch files path
+untouched_root="$git_root/_untouched"
 
-# Check if there is any staged .sketch file
+# Array of all staged files
+git_diff=`git diff --name-only --cached | grep ".sketch$"`
+
+# Check if any Sketch file is staged
 if [[ ${git_diff[0]} == '' ]]
 then
-    echo "No Sketch file staged."
+  echo "No Sketch file staged."
 else
-  while read sketch_file
+  while read staged_sketch
   do
+
     # Absolute Sketch file path
-    sketch_file_path="$git_root/$sketch_file"
-    # Unzipped directory
-    unzipped_directory="$git_root/_unzipped/$sketch_file"
-    # Untouched directory
-    untouched_directory="$git_root/_untouched"
-    # Untouched Sketch file
-    untouched_path="$untouched_directory/$sketch_file"
-    echo "$sketch_file"
+    sketch="$git_root/$staged_sketch"
+    # Unzipped Sketch file directory path
+    unzipped_directory="$unzipped_root/$staged_sketch"
+    # Untouched Sketch file path
+    untouched_sketch="$untouched_root/$staged_sketch"
+    # Untouched Sketch file directory path
+    untouched_directory=`dirname "$untouched_sketch"`
+
+    echo "Processing '`basename $sketch`'."
+
     # Copy untouched Sketch file to untouched folder
-    if mkdir -p "$untouched_path"
+    if mkdir -p "$untouched_directory"
     then
-      if cp "$sketch_file_path" "$untouched_path"
+      if cp "$sketch" "$untouched_sketch"
       then
-        echo "Untouched '$sketch_file' backed up."
+        echo "  Untouched '`basename $sketch`' backed up."
       else
-        echo "Couldn't copy untouched '$sketch_file'."
+        echo "  Couldn't copy untouched '`basename $sketch`'."
         exit 1
       fi
     else
-      echo "Couldn't create untouched directory."
+      echo "  Couldn't create '$untouched_root' directory."
       exit 1
     fi
     # Stage untouched file
-    git add "$untouched_path"
+    git add "$untouched_sketch"
+
     # Delete existing directory
     rm -rf "$unzipped_directory"
     # If Sketch file wasn't deleted
-    if ! git diff --summary --cached -- $sketch_file | grep "delete" 2>&1 > /dev/null
+    if ! git diff --summary --cached -- $staged_sketch | grep "delete" 2>&1 > /dev/null
     then
       # Create directory
       if mkdir -p "$unzipped_directory"
       then
         if cd "$unzipped_directory"
         then
-          if unzip "$sketch_file_path"
+          # Unzip Sketch file
+          if unzip -q "$sketch"
           then
-            echo "'$sketch_file' unzipped."
+            echo "  '`basename $sketch`' unzipped."
+            # Prettify all JSON files
             for json_file in $(find . -name "*.json")
             do
               if python3 -m json.tool "$json_file" "$json_file".pretty
               then
                 if mv "$json_file".pretty "$json_file"
                 then
-                  echo "'$json_file' prettified."
+                  echo "  '$json_file' prettified."
                 else
-                  echo "Couldn't move prettified '$json_file'."
+                  echo "  Couldn't move prettified '$json_file'."
                   rm -rf "$unzipped_directory"
                   exit 1
                 fi
               else
-                echo "Couldn't prettify '$json_file'."
+                echo "  Couldn't prettify '$json_file'."
                 rm -rf "$unzipped_directory"
                 exit 1
               fi
             done
           else
-            echo "Couldn't unzip '$sketch_file'."
+            echo "  Couldn't unzip '`basename $sketch`'."
             rm -rf "$unzipped_directory"
             exit 1
           fi
           cd "$git_root"
         else
-          echo "Couldn't change directory to '$unzipped_directory'."
+          echo "  Couldn't change directory to '$unzipped_directory'."
           exit 1
         fi
       else
-        echo "Couldn't create directory '$unzipped_directory'."
+        echo "  Couldn't create directory '$unzipped_directory'."
         exit 1
       fi
     fi
     git add "$unzipped_directory/*"
+
   done <<< "$git_diff"
 fi
